---
title: "DIF interface"
output: html_document
---

The jamovi interface has a number of options:

1.      title: Items       type: Variables
2.      title: Grouping Variable       type: Variable
3.      title: Matching Variable       type: Variable
4.      title: Anchor Items      type: Variables
5.      title: Group Type      type: List
    	  options:
    	  - name: group
        	title: Discrete Groups
    	  - name: cont
        	title: Continuous Groups
6.      title: Evaluation Scale      type: List
    	  options:
        	- name: zt
        	  title: Zumbo-Thomas
        	- name: jg
        	  title: Jodoin-Gierl
7.       title: Design Analysis
8.       title: Flagged items only
9.       title: Bootstrap N      type: Number
10.       title: Observed Power
11.      title: Hypothesized True Effect Size      type: String
12.      title: Type
    	  options:
        - title: Uniform DIF
        - title: Non-Uniform DIF
        - title: Uniform and Non-Uniform DIF
13.      title: Flagging Criterion
    	  options:
    	  - name: "Wald"
    	  - name: "LRT"
14.      title: Alpha      type: Number
15.       title: Item Purification
16.        title: Number of Iterations      type: Number
17.        title: P-value Adjustment method
    	  options: 
        	- name: bonferroni
        	- name: holm
        	- name: hochberg
        	- name: hommel
        	- name: BH
        	- name: BY
        	- name: none
18.       name: plotVarsICC      type: Variables