---
title: "Test ROC - Comprehensive"
nickname: testROCcomprehensive
topic: testROC
category: measureDiagnostics
output: 
  html_document:
     includes:
         in_header: ganalytics.txt
     toc: true
     toc_float:
        collapsed: false
---

```{r echo=FALSE,results='hide'}
source("../R/functions.R")
```

The following is a comprehensive overview of the available options in the Test ROC module. For information on getting started, see here:

`r list_pages(nickname = "testROCFintroduction")`

## Calculations

The TestROC module is built on top of "cutpointR", which is a well-documented R package by Christian Thiele [LINK]. As such, the best documentation on the calculations performed by any of the options below is found in the cutpointR package documentation. In addition, any requests for changes in the way calculations are performed are best directed to cutpointR. If/when they are implemented there, the TestROC package will be automatically updated.

## Options

### 1. title: Dependent Variable      type: Variables


### 2. Class Variable      type: Variable


### 3. Group Variable      type: Variable

### 4. Method
      options: 
        Custom cut score
        Maximize metric
        Minimize metric
        Maximize metric (LOESS)
        Minimize metric (LOESS)
        Maximize metric (spline)
        Minimize metric (spline)
        Maximize metric (boot)
        Minimize metric (boot)
        Maximize Youden-Index (Kernel smoothed)
        Maximize Youden-Index (Parametric normal)
        default: maximize_metric

`Method` determines how the optimal cutpoint will be determined after calculating the `Metric` (below). The default is simply `Maximize Metric`, which means that the cutpoint with the maximum value for `Metric` will be chosen as the optimal cutpoint. The options in brackets, `LOESS`, `spline`, `boot`, `Kernel smoothed`, and `Parametric normal` refer to different smoothing operations which may be carried out on the metric prior to selecting the respective max/min value.

### 5. All observed scores

If `All observed scores` is selected, results table will return statistics for all observed measure scores in the data.
      
### 6. Specify cut score      type: String

`Specify cut score` will be ignored unless the `Custom Cut Score` option for `Method` (above) is chosen. This option is used to return only the results for a single specified observed score.

### 7. Metric      type: List
      options:
        Sum Sens-Spec
        Accuracy
        Youden-Index
        Sum: Sens/Spec
        Sum: PPV/NPV
        Prod: Sens/Spec
        Prod: PPV/NPV
        Cohen's Kappa
        Abs. d: Sens/Spec
        ROC
        Abs. d: PPV/NPV
        Chi-squared
        Odds Ratio
        Risk Ratio
        Misclassification Cost
        Total Utility
        F1 score
        
`Metric` refers to the statistic/value that is to be calculated and used by `Method` for selecting the optimal cutpoint(s).

### 8. Bootstrap runs      type: Number

*Not yet implemented. Please notify the author if this feature would be useful to you*

`Bootstrap runs` is the number of bootstrap samples will be used to assess the variability and the out-of-sample performance. If used, bootstrap samples will be drawn and the optimal cutpoint
using method will be determined this way. Additionally, as a way of internal validation, the function in metric will be used to score the out-of-bag predictions using the cutpoints determined by method.
Various default metrics are always included in the bootstrap results.

### 9. Ties
      options:
        All optimal cutpoints
        Mean optimal cutpoint
        Median optimal cutpoint

### 10. Direction (relative to optimal cutpoint)
      options:
        ">="
        "<="

`Direction` refers to the direction of the observed score relative to the optimal cutpoint. That is, whether the cutpoint should be a 'floor' or a 'ceiling'.

### 11. ROC
      default: True
      
Selecting the `ROC` option will return an ROC curve for each dependent variable and group.

### 12. Standard error bars
      default: True
      
If `ROC` has been selected, `Standard error bars` is used to show approximated standard error ranges using LOESS smoothing.

### 13. LOESS Smoothing
      default: True

Selecting the `LOESS Smoothing` option will overlay a LOESS smoothed regression line on the ROC curve.

### 14. Sensitivity-Specificity Tables
      default: False
      
`Sensitivity-Specificity Tables` is used to display the raw data at used to calculate sensitivity and specificity. This option may be useful for checking data if the results of the optimal cutpoints or ROC curve are not as expected.

# Examples

Some worked out examples of analyses carried out with jamovi PsychoPDA are posted here (more to come):

`r include_examples("testROC")`

`r issues()`