---
title: "Troubleshooting PsychoPDA"
output: 
  html_document:
     toc: true
     toc_float:
        collapsed: false

---
  


# Common Issues

### Variable names:
`r #version("0.1.0")`

If variables have names not following R standard, some problem may still appear.

### Solution:
Use variable names without space, parentheses or brackets, etc. 

`r #version(">0.1.0")`

# Binary DIF

**Error: Can only apply contrasts to data with 2 or more levels**

This is an error that _usually_ comes from attempting to fit a logistic model in R to data which does not have at least two different responses for each grouping variable.

For example, in data coded [0, 1] for incorrect and correct responses and two groups [m, f], it might be the case that no `f` in your data set responded inorrectly, meaning there are no `f` in the data with response `0`. This will break the `glm()` function.

Ensure that there are no rows/columns in your data with no responses, and that there are no groups who only respond in a single way.

If this doesn't seem to be the case for you, you may have encountered a bug: please feel free to contact me using a method at the bottom of this page.

# Mean Differences Design Analysis

nothing yet

# Correlation Design Analysis

nothing yet

`r issues()`
